import mongoose from "mongoose";
const Schema = mongoose.Schema;

const postSchema = new Schema({

    //this will be generated by the server.
    op_id: {
        type: String,
        required: true,
        unique: true
    },

    username: {
        type: String,
        required: true,
    },

    title: {  //this is just for setting up the name of the thread, which will starts when the op will be created.
        type: String,
        required: true,
    },

    textContent: {
        type: String,
        required: false,
    },

    media: {
        type: String
    },

    upVote: {
        type: Number,
        default: 0
    },

    downVote: {
        type: Number,
        default: 0
    },

    //refrence to the thread
    thread_id: {
        type: Schema.Types.ObjectId,
        ref: 'threadModels',
    },

    replies: [{
        type: mongoose.Types.ObjectId,
        ref: 'replies'
    }],

    board: {
        type: Schema.Types.ObjectId,
        ref: 'BoardCategory', // This is the key part that links to the Category model
        required: true,
    },

}, {
    timestamps: true,
});

const op_postModel = mongoose.model('op_posts', postSchema);

export default op_postModel;